### ISSUE TITLE
Pre-trained weights availability

### ISSUE THREAD

**Issue by danigoju** [mberkay0/clothing-segmentation#1]
Good afternoon and thank you very much for your work @mberkay0 😄 

I am working in a personal project where your work would help me a lot, so are the pre-trained weights of the model available? If so, could you please share them with me? This would be very helpful, as I wouldn't need to train the model, given that you already did.

Best regards,
Dani

**Comment by mberkay0** [comment]
Thank you, @danigoju. Regrettably, since my project is quite old, I do not have any pre-trained weights. Perhaps you could reduce the data and fine-tune the model. In this way, you may achieve similar performance in a short time. Good luck with your project.
All the best.
